### ISSUE TITLE
Which country is used for the test? 

### ISSUE THREAD

**Issue by NelsonHernandezM** [NeuroQuestAi/five-factor-e#1]
Hi, i have 2 questions
Which  country is used for the test?  
How can you get each score of the letters ocean?

**Comment by edersoncorbari** [comment]
Hi Nelson, 

About your questions:

- The country is not taken into account in the algorithm calculations, but it is an option that you can put in your system.
- The big-five and its 30 facets are calculated at runtime by the algorithm.

Please let me know if you have any questions.

Cheers,
EDMC.

**Comment by edersoncorbari** [comment]
> Hi Nelson,
> 
> About your questions:
> 
> * The country is not taken into account in the algorithm calculations, but it is an option that you can put in your system.
> * The big-five and its 30 facets are calculated at runtime by the algorithm.
> 
> Please let me know if you have any questions.
> 
> Cheers, EDMC.

Hi Nelson,

About your questions:

The country is not taken into account in the algorithm calculations, but it is an option that you can put in your system.
The big-five and its 30 facets are calculated at runtime by the algorithm.
Please let me know if you have any questions.

Cheers,
EDMC.
